//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RISIQueryService.RISIService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RISIService.IRISISqlContract")]
    public interface IRISISqlContract {
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IRISISqlContract/GetMachineName", ReplyAction="http://tempuri.org/IRISISqlContract/GetMachineNameResponse")]
        string GetMachineName();
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IRISISqlContract/GetSettings", ReplyAction="http://tempuri.org/IRISISqlContract/GetSettingsResponse")]
        string GetSettings();
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IRISISqlContract/ExecuteSQLQuery", ReplyAction="http://tempuri.org/IRISISqlContract/ExecuteSQLQueryResponse")]
        byte[] ExecuteSQLQuery(string query);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRISISqlContractChannel : RISIQueryService.RISIService.IRISISqlContract, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RISISqlContractClient : System.ServiceModel.ClientBase<RISIQueryService.RISIService.IRISISqlContract>, RISIQueryService.RISIService.IRISISqlContract {
        
        public RISISqlContractClient() {
        }
        
        public RISISqlContractClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RISISqlContractClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RISISqlContractClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RISISqlContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetMachineName() {
            return base.Channel.GetMachineName();
        }
        
        public string GetSettings() {
            return base.Channel.GetSettings();
        }
        
        public byte[] ExecuteSQLQuery(string query) {
            return base.Channel.ExecuteSQLQuery(query);
        }
    }
}
