//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.RISIQueryService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RISIQueryService.IRISIQueryContract")]
    public interface IRISIQueryContract {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRISIQueryContract/Subscribe", ReplyAction="http://tempuri.org/IRISIQueryContract/SubscribeResponse")]
        void Subscribe(string uri);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRISIQueryContract/Subscribe", ReplyAction="http://tempuri.org/IRISIQueryContract/SubscribeResponse")]
        System.Threading.Tasks.Task SubscribeAsync(string uri);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRISIQueryContract/PostQuery", ReplyAction="http://tempuri.org/IRISIQueryContract/PostQueryResponse")]
        void PostQuery(RISIQueryService.QueryData data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRISIQueryContract/PostQuery", ReplyAction="http://tempuri.org/IRISIQueryContract/PostQueryResponse")]
        System.Threading.Tasks.Task PostQueryAsync(RISIQueryService.QueryData data);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRISIQueryContractChannel : Test.RISIQueryService.IRISIQueryContract, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RISIQueryContractClient : System.ServiceModel.ClientBase<Test.RISIQueryService.IRISIQueryContract>, Test.RISIQueryService.IRISIQueryContract {
        
        public RISIQueryContractClient() {
        }
        
        public RISIQueryContractClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RISIQueryContractClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RISIQueryContractClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RISIQueryContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Subscribe(string uri) {
            base.Channel.Subscribe(uri);
        }
        
        public System.Threading.Tasks.Task SubscribeAsync(string uri) {
            return base.Channel.SubscribeAsync(uri);
        }
        
        public void PostQuery(RISIQueryService.QueryData data) {
            base.Channel.PostQuery(data);
        }
        
        public System.Threading.Tasks.Task PostQueryAsync(RISIQueryService.QueryData data) {
            return base.Channel.PostQueryAsync(data);
        }
    }
}
